Aoc day three
DeniseRijborz/Scalaworkshop pull request #4
Opened 2022-10-06 17:28 UTC by DeniseRijborz

2022-10-07 11:24 UTC, nmcb requested changes
minor comments - the implementation is correct though not very idiomatically modeled - the problem is an excellent one to learn how modelling helps to make implementational intent of code clearer - you could rewrite the solution eg. employing the following case classes

```
case class Loc(x: Int, y: Int)

case class Area(cur: Loc = Loc(0, 0), houses: Map[Loc,Int] = Map(Loc(0, 0) -> 1))
```

2022-10-07 11:24 UTC, nmcb commented on aoc/src/main/scala/aoc2015/Day03.scala
> +      case (x, i) =>
syntax preference on: if statements as part of the match cases; and the `+` operator for string concatenation, ie.

```
lines.zipWithIndex.foreach {
  case (x,i) if (i % 2 == 0) => evenDirections = evenDirections + x.toString
  case (x,i)                 => unevenDirections = unevenDirections + x.toString
```

2022-10-07 11:24 UTC, nmcb commented on aoc/src/main/scala/aoc2015/Day03.scala
> +    var evenDirections: String = ""
usage of `var`s is frowned upon - see whether you can rewrite the `foreach` loop with a `foldLeft` that calculates the direction strings as immutable values while traversing the lines with indexes

2022-10-07 11:24 UTC, nmcb commented on aoc/src/main/scala/aoc2015/Day03.scala
> +    if (directions.isEmpty) {
perhaps implement the head direction part of the if/else tree with pattern matching on `Char`s, ie. between single-quotes

```
directions.head match
  case '^' =>
    val newx = currentx + 0
    val newy = currenty + 1
    location(newx, newy, directions.tail, xAxis :+ newx, yAxis :+ newy)
  case 'v' =>
    ...
```

2022-10-13 13:19 UTC, DeniseRijborz commented
> minor comments - the implementation is correct though not very idiomatically modeled - the problem is an excellent one to learn how modelling helps to make implementational intent of code clearer - you could rewrite the solution eg. employing the following case classes
> 
> ```
> case class Loc(x: Int, y: Int)
> 
> case class Area(cur: Loc = Loc(0, 0), houses: Map[Loc,Int] = Map(Loc(0, 0) -> 1))
> ```

I changed some code based on the feedback, but I still have to look at using case classes.

2022-10-13 14:59 UTC, nmcb requested changes
lgtm - very neat - a little heavy on the updates though; this would be a good one to solve with case classes, eg.the following class models `Pos` and `Area`; and methods `moveTo` and `next` would move the command interpretation into the `Area` class:

```
  case class Loc(x: Int, y: Int)

  case class Area(cur: Loc = Loc(0, 0), houses: Map[Loc,Int] = Map(Loc(0, 0) -> 1)):

    private def moveTo(l: Loc): Area =
      houses.get(l) match
        case Some(c) => copy(cur = l, houses = houses.updated(l, c + 1))
        case None    => copy(cur = l, houses = houses + (l -> 1))

    def next(c: Char): Area =
      c match
        case '>' => { val loc = cur.copy(x = cur.x + 1) ; moveTo(loc) }
        case '<' => { val loc = cur.copy(x = cur.x - 1) ; moveTo(loc) }
        case '^' => { val loc = cur.copy(y = cur.y + 1) ; moveTo(loc) }
        case 'v' => { val loc = cur.copy(y = cur.y - 1) ; moveTo(loc) }
```

an `Area` wraps the current location of Santa (or RoboSanta) and a map of houses containing the current state of presents delivered. the `Char` command list can then be folded over with an initial area, subsequently updating the whole area.

2022-10-13 15:01 UTC, nmcb commented
this ☝️ is only one possible implementation ofc - but it shows the use of case classes to model the current state of the problem as a whole.

2022-10-20 13:45 UTC, nmcb approved these changes

2022-10-20 13:48 UTC, merged